apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aci-pong.fullname" . }}-webpages
  labels:
    app: {{ include "aci-pong.name" . }}
data:
  webpages.txt: |-
{{ .Values.webpages.data | indent 4 }}