apiVersion: v1
kind: Service
metadata:
  name: {{ include "aci-pong.fullname" . }}
  labels:
    app: {{ include "aci-pong.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "aci-pong.name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aci-pong.fullname" . }}
  labels:
    app: {{ include "aci-pong.name" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ include "aci-pong.fullname" . }}
  endpoints:
    - targetPort: http
      interval: 30s